# Main composition file for VerySecure FTP Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:

   # FTP Server Container
  ftpserver:
    container_name: ftpserver
    # Map container ports 8080 and 8081.
    ports:
      - '20:20' # FTP Control Connection Port
      - '21:21' # FTP Data Connection Port
    # Mount local directories as volumes inside the container:
    volumes:
      - "./share/:/data/ftp/"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - FTP_USER=capacita
      - FTP_PASSWORD=capacita
      - FTP_UID=1000
      - FTP_GID=1000
      - FTP_PATH=/data/ftp/
